export { default as AlphabetTable } from "./AlphabetTable";
export { default as CountriesNationalitiesTable } from "./CountriesNationalities";
export { default as GrammarTable } from "./GrammarTable";
export { default as ExamplesTable } from "./ExemplesTable";
export { default as ConjugationTable } from "./ConjugationTable";
export { default as AdjectivesTable } from "./AdjectivesTable";
export { default as NumeralsTable } from "./NumeralsTable";
export { default as GlossaryTable } from "./GlossaryTable";
export { default as PronounTable } from "./PronounTable";
