export {
  tableClassName,
  tableWithoutBorderLayoutAutoClassName,
  tdClassName,
  tableWithoutBorderClassName,
  tdColorizedClassName,
  tdColorizedWithoutBorderClassName,
  thClassName,
  thColorizedClassName,
  getColorizedThClassName,
  getColorizedFirstTdClassName,
  getColorizedExceptFirstTdClassName,
  getColorizedItalicTdClassName,
  textCenterClassName,
} from "./classNamesRules";
