// import { NumeralsTableBlock } from "@/types";
import { TablesProps } from "@/types";

export const cardinalOrdinalNumeralsTable: TablesProps = {
  slug: "lesson-2",
  type: "cardinal-ordinal-numerals-table",
  content: {
    subtitle: [
      `Число`,
      `Количественное числительное`,
      `Порядковое числительное`,
    ],
    words: [
      { numbers: 1, cardinal: "е\u0301ден", ordinal: "прв" },
      { numbers: 2, cardinal: "два/две", ordinal: "втор" },
      { numbers: 3, cardinal: "три", ordinal: "трет" },
      { numbers: 4, cardinal: "че́тири", ordinal: "че́тврт" },
      { numbers: 5, cardinal: "пет", ordinal: "пе́тти" },
      { numbers: 6, cardinal: "шест", ordinal: "ше́сти" },
      { numbers: 7, cardinal: "се́дум", ordinal: "се́дми" },
      { numbers: 8, cardinal: "о́сум", ordinal: "о́сми" },
      { numbers: 9, cardinal: "де́вет", ordinal: "де́ветти" },
      { numbers: 10, cardinal: "де́сет", ordinal: "де́сети" },
      { numbers: 11, cardinal: "единае́сет", ordinal: "единае́сети" },
      { numbers: 12, cardinal: "дванае́сет", ordinal: "дванае́сети" },
      { numbers: 13, cardinal: "тринае́сет", ordinal: "тринае́сети" },
      { numbers: 14, cardinal: "четиринае́сет", ordinal: "четиринае́сети" },
      { numbers: 15, cardinal: "петнае́сет", ordinal: "петнае́сети" },
      { numbers: 16, cardinal: "шеснае́сет", ordinal: "шеснае́сети" },
      { numbers: 17, cardinal: "седумнае́сет", ordinal: "седумнае́сети" },
      { numbers: 18, cardinal: "осумнае́сет", ordinal: "осумнае́сети" },
      { numbers: 19, cardinal: "деветнае́сет", ordinal: "деветнае́сети" },
      { numbers: 20, cardinal: "два́есет", ordinal: "два́есети" },
      { numbers: 21, cardinal: "два́есет и е́ден", ordinal: "два́есет и прв" },
      { numbers: 30, cardinal: "три́есет", ordinal: "три́есети" },
      { numbers: 40, cardinal: "четири́есет", ordinal: "четири́есети" },
      { numbers: 50, cardinal: "пе́десет", ordinal: "пе́десети" },
      { numbers: 60, cardinal: "ше́есет", ordinal: "ше́есети" },
      { numbers: 70, cardinal: "седу́мдесет", ordinal: "седу́мдеесети" },
      { numbers: 80, cardinal: "осу́мдесет", ordinal: "осу́мдеесети" },
      { numbers: 90, cardinal: "деве́десет", ordinal: "деве́деесети" },
      { numbers: 100, cardinal: "сто", ordinal: "сто́тен/сто́ти" },
      { numbers: 101, cardinal: "сто и е́ден", ordinal: "сто и прв" },
      { numbers: 200, cardinal: "две́сте", ordinal: "две́стотен/две́стоти" },
      { numbers: 300, cardinal: "три́ста", ordinal: "три́стотен/три́стоти" },
      {
        numbers: 400,
        cardinal: "четиристо́тини",
        ordinal: "четири́стотен/четири́стоти",
      },
      { numbers: 500, cardinal: "петсто́тини", ordinal: "пе́тстотен/пе́тстоти" },
      { numbers: 600, cardinal: "шесто́тини", ordinal: "ше́стотен/ше́стоти" },
      {
        numbers: 700,
        cardinal: "седумсто́тини",
        ordinal: "седу́мстотен/седу́мстоти",
      },
      {
        numbers: 800,
        cardinal: "осумсто́тини",
        ordinal: "осу́мстотен/осу́мстоти",
      },
      {
        numbers: 900,
        cardinal: "деветсто́тини",
        ordinal: "деве́тстотен/деве́тстоти",
      },
      { numbers: 1000, cardinal: "и́љада", ordinal: "и́љаден/и́љадити" },
      { numbers: 1001, cardinal: "и́љада и е́ден", ordinal: "и́љада и прв" },
      { numbers: 2000, cardinal: "две и́љади", ordinal: "две́иљаден/две́иљадити" },
    ],
  },
};
