import { DialogueBlockProps } from "@/types";

export const dialogueBlock: DialogueBlockProps = {
  slug: `lesson-5`,
  sections: [
    {
      type: "lecture",
      subtitle: {
        ru: "ДИАЛОГ",
        mkd: "ДИЈАЛОГ",
      },
      content: {
        description: {
          mkd: `На*таша и И*ван се умо*рени од проше*тката и о*дат на ру*чек.`,
          ru: `Наташа и Иван устали после прогулки и идут на обед.`,
        },
        dialogue: [
          {
            speaker: {
              id: `waiter`,
              mkd: `Ке*лнерот:`,
              ru: `Официант:`,
            },
            mkd: [
              `До*бар де*н! Пове*лете. Са*кате вна*тре и*ли на*двор?`,
              `Не, во рестора*ните пуше*њето е забра*нето. Мо*же да се пу*ши са*мо на те*раса.`,
              `Мо*же да се*днете се*каде о*свен о*наа ма*са де*сно, резерви*рана е.`,
              `Пове*лете ме*ни.`,
              `То*гаш за пердjа*дење ви перпора*чувам а*jвар и си*рење, шо*пска са*лата за два*jца
              и*ли е*дна шо*пска са*лата за вас и е*дна маке*донска са*лата за госпо*ѓата.`,
              `И*маме ра*злично ме*со на ска*ра. И се*како ви препора*чувам да про*бате
              турли*-та*ва и та*вче-гра*вче.`,
              `Турли*-та*ва се пра*ви од зе*ленчук и ме*со, та*вче-гра*вче од пе*чен грав.`,
              `За со са*лата мо*же да зе*мете е*дна ра*киjа, а по*тоа пи*во и*ли ви*но по ваш
              и*збор.`,
              `Ќе тре*ба да поче*кате ма*лку за турли*-та*ва, се дру*го ќе би*де го*тово мно*гу
              бр*зо.`,
              `Пове*лете, пердjаде*њата и пиjала*ците.`,
              `Се изви*нувам, ве*днаш.`,
              `Пове*лете. Ќе пла*ќате со ка*ртичка и*ли во го*тово?`,
              `Се ра*збирам. Са*мо мо*мент. Пове*лете.`,
              `Ви благо*дарам и при*jатно.`,
            ],
            ru: [
              `Добрый день! Проходите. Выхотите внутри или снаружи?`,
              `Нет, в ресторанах курение запрещено. Можно курить только на террасе.`,
              `Вы можете сесть везде, кроме того столика справа. Он зарезервирован.`,
              `Пожалуйта, меню.`,
              `Тогда на закуску советую айвар и брынзу, шопский салат на двоих или один шопский салат для вас и один македонский салат для
              дамы.`,
              `У нас есть разное мясо на гриле. И, конечно же, советую вам попробовать турли-таву и тавче-гравче.`,
              `Турли-тава из овощей и мяса, тавче-гравче из печенной фосоли.`,
              `С салатом можете взять ракию, а потом пиво или вино на выбор.`,
              `Придется немного подождать турли-таву, все остальное будет готовиться очень быстро.`,
              `Пожалуйста, закуски и напитки.`,
              `Извените, секунду.`,
              `Пожалуйста. Вы будете платить карточкой или наличными?`,
              `Разумеется. Менуточку. Пожалуйста.`,
              `Спасибо и до свиданья.`,
            ],
          },
          {
            speaker: {
              id: `ivan`,
              mkd: `И*ван:`,
              ru: `Иван:`,
            },
            mkd: [
              `А се пу*ши ли вна*тре?`,
              `То*гаш на*двор. Е*дна ма*са за два*jца, ве мо*лам.`,
              `Што ќе ни перпара*чате? Са*кам да ги про*бам наjдо*брите маке*донски специjалите*ти.`,
              `А за гла*вно jа*дење?`,
              `Од што се пра*ват?`,
              `А за пи*ење?`,
              `На*таша, што ми*слиш?`,
              `Ве мо*лам, а*jвар со си*рење е*дна ма*ла шо*пска, турли*-та*ва, е*дна жо*лта
              ра*киjа, поло*вина ли*тар гази*рана во*да и е*дно подпе*чено ле*пче. Ко*лку
              вре*ме ќе че*каме?`,
              `До*бар а*петит.`,
              `Сме*тка ве мо*лам.`,
              `Со ка*ртичка. На*таша и*маш па*ри во го*тово за ба*кшиш?`,
              `Фа*ла. Мно*гу у*баво jа*дење. При*jатно.`,
            ],
            ru: [
              `Внутри можно курить?`,
              `Тогда снаружи. Столик на двоих, пожалуйста.`,
              `Что вы нам посоветуете? Я хочу попробовать лучшие македонские блюда.`,
              `А на второе?`,
              `Из чего они готовятся?`,
              `А попить?`,
              `Наташа, что ты думаешь?`,
              `Пожалуйста, айвар с брынзой, маленькая порция шопского салата, турли-тава, рюмка жолтой ракии, пол литра газированной воды и 
              поджаренный хлеб. Как долго мы будем ждать?`,
              `Приятного аппетита.`,
              `Счет пожалуйста. Карточкой. Наташа, у тебя есть наличные на чаевые?`,
              `Спасибо. Очень вкусно. До свидания.`,
            ],
          },
          {
            speaker: {
              id: `natasha`,
              mkd: `На*таша:`,
              ru: `Наташа:`,
            },
            mkd: [
              `Ми се до*паѓа о*ваа.`,
              `Jас ќе зе*мам е*дна ма*ла маке*донска са*лата, но ќе ве за*молам без ма*гдонос — и*мам
              але*ргиja. Де*сет кеба*пчиња и ча*ша бе*ло су*во ви*но.`,
              `Изви*нете, да*ли мо*жете да ja сме*ните о*ваа ви*љушка? Не*чиста е.`,
              `До*бар а*петит.`,
              `Да, но са*мо 500. Изви*нете, да*ли мо*жете да ни раси*тните 500 де*нари по сто?`,
            ],
            ru: [
              `Мне нравится вот этот.`,
              `Я возьму маленькую порцию македонского салата, но попрошу вас без петрушки — у меня аллергия. Десять кебабче и бокал
              белого сухого вина.`,
              `Извините, вы можете поменять эту вилку? Она грязная.`,
              `Приятного аппетита.`,
              `Да, но только 500. Извините, вы можете нам поменять 500 денар по сто?`,
            ],
          },
          {
            speaker: {
              id: `description`,
            },
            mkd: [`<em>По 10 ми*нути.</em>`, `<em>По 40 ми*нути.</em>`],
            ru: [
              `<em>Десять минут спустя.</em>`,
              `<em>Сорок минут спустя.</em>`,
            ],
          },
        ],
        dialogueOrder: [
          { speakerId: "waiter", language: "ru", replyIndex: 0 },
          { speakerId: "waiter", language: "mkd", replyIndex: 0 },
          { speakerId: "ivan", language: "ru", replyIndex: 0 },
          { speakerId: "ivan", language: "mkd", replyIndex: 0 },
          { speakerId: "waiter", language: "ru", replyIndex: 1 },
          { speakerId: "waiter", language: "mkd", replyIndex: 1 },
          { speakerId: "ivan", language: "ru", replyIndex: 1 },
          { speakerId: "ivan", language: "mkd", replyIndex: 1 },
          { speakerId: "waiter", language: "ru", replyIndex: 2 },
          { speakerId: "waiter", language: "mkd", replyIndex: 2 },
          { speakerId: "natasha", language: "ru", replyIndex: 0 },
          { speakerId: "natasha", language: "mkd", replyIndex: 0 },
          { speakerId: "waiter", language: "ru", replyIndex: 3 },
          { speakerId: "waiter", language: "mkd", replyIndex: 3 },
          { speakerId: "ivan", language: "ru", replyIndex: 2 },
          { speakerId: "ivan", language: "mkd", replyIndex: 2 },
          { speakerId: "waiter", language: "ru", replyIndex: 4 },
          { speakerId: "waiter", language: "mkd", replyIndex: 4 },
          { speakerId: "ivan", language: "ru", replyIndex: 3 },
          { speakerId: "ivan", language: "mkd", replyIndex: 3 },
          { speakerId: "waiter", language: "ru", replyIndex: 5 },
          { speakerId: "waiter", language: "mkd", replyIndex: 5 },
          { speakerId: "ivan", language: "ru", replyIndex: 4 },
          { speakerId: "ivan", language: "mkd", replyIndex: 4 },
          { speakerId: "waiter", language: "ru", replyIndex: 6 },
          { speakerId: "waiter", language: "mkd", replyIndex: 6 },
          { speakerId: "ivan", language: "ru", replyIndex: 5 },
          { speakerId: "ivan", language: "mkd", replyIndex: 5 },
          { speakerId: "waiter", language: "ru", replyIndex: 7 },
          { speakerId: "waiter", language: "mkd", replyIndex: 7 },
          { speakerId: "ivan", language: "ru", replyIndex: 6 },
          { speakerId: "ivan", language: "mkd", replyIndex: 6 },
          { speakerId: "natasha", language: "ru", replyIndex: 1 },
          { speakerId: "natasha", language: "mkd", replyIndex: 1 },
          { speakerId: "ivan", language: "ru", replyIndex: 7 },
          { speakerId: "ivan", language: "mkd", replyIndex: 7 },
          { speakerId: "waiter", language: "ru", replyIndex: 8 },
          { speakerId: "waiter", language: "mkd", replyIndex: 8 },

          { speakerId: "description", language: "ru", replyIndex: 0 },
          { speakerId: "description", language: "mkd", replyIndex: 0 },

          { speakerId: "waiter", language: "ru", replyIndex: 9 },
          { speakerId: "waiter", language: "mkd", replyIndex: 9 },
          { speakerId: "natasha", language: "ru", replyIndex: 2 },
          { speakerId: "natasha", language: "mkd", replyIndex: 2 },
          { speakerId: "waiter", language: "ru", replyIndex: 10 },
          { speakerId: "waiter", language: "mkd", replyIndex: 10 },
          { speakerId: "natasha", language: "ru", replyIndex: 3 },
          { speakerId: "natasha", language: "mkd", replyIndex: 3 },
          { speakerId: "ivan", language: "ru", replyIndex: 8 },
          { speakerId: "ivan", language: "mkd", replyIndex: 8 },

          { speakerId: "description", language: "ru", replyIndex: 1 },
          { speakerId: "description", language: "mkd", replyIndex: 1 },

          { speakerId: "ivan", language: "ru", replyIndex: 9 },
          { speakerId: "ivan", language: "mkd", replyIndex: 9 },
          { speakerId: "waiter", language: "ru", replyIndex: 11 },
          { speakerId: "waiter", language: "mkd", replyIndex: 11 },
          { speakerId: "ivan", language: "ru", replyIndex: 10 },
          { speakerId: "ivan", language: "mkd", replyIndex: 10 },
          { speakerId: "natasha", language: "ru", replyIndex: 4 },
          { speakerId: "natasha", language: "mkd", replyIndex: 4 },
          { speakerId: "waiter", language: "ru", replyIndex: 12 },
          { speakerId: "waiter", language: "mkd", replyIndex: 12 },
          { speakerId: "ivan", language: "ru", replyIndex: 11 },
          { speakerId: "ivan", language: "mkd", replyIndex: 11 },
          { speakerId: "waiter", language: "ru", replyIndex: 13 },
          { speakerId: "waiter", language: "mkd", replyIndex: 13 },
        ],
      },
    },
  ],
};
